name: Prettier Formatting

on:
  push:
    branches:
      - main
      - Add-Unit-Tests
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --write .

      - name: Check for changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes detected"
          else
            git commit -m "Apply Prettier formatting"
            git push
          fi
