name: Trigger Frontend E2E After Backend Deployment

on:
  workflow_run:
    workflows: ["Deploy Backend App"]  # Name of your backend deployment workflow
    types:
      - completed

jobs:
  trigger-frontend-e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger frontend end-to-end tests
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/nefotatariCS/ExpensesAppFe/dispatches \
          -d '{"event_type":"deploy-backend-trigger"}'