name: Run Backend Unit Tests

on:
  push:
    branches:
      - '*'      # This matches all branches
    paths-ignore:
      - 'main/**'  # Exclude the main branch from triggering the workflow
jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          npm install

      - name: Run backend unit tests
        run: |
          npm test

